image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      flutter channel beta
      flutter upgrade

      flutter config --enable-web
      flutter config --android-sdk /home/gitpod/androidsdk
      yes | flutter doctor --android-licenses

      flutter doctor

      flutter pub get

      flutter build -v bundle
      flutter build -v web
      flutter build -v appbundle
      flutter build -v apk
      
  - command: |
      flutter devices
      sleep 10
      flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0


ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: open-preview
    # flutter
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
