image:
  file: .gitpod.Dockerfile
tasks:
  - before: sudo mount -t tmpfs shm -osize=4096m /dev/shm
  
  - init: |
      flutter channel beta
      flutter upgrade

      flutter config --enable-web
      flutter config --android-sdk /home/gitpod/androidsdk
      yes | flutter doctor --android-licenses

      flutter doctor
      
  - command: |
      flutter devices
      
      flutter pub get
      flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0


ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: open-preview
    # flutter
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
